### ISSUE TITLE
The link `https://docs.opentermsarchive.org/how-to/navigate-history/` in the repository returns a 404 error

### ISSUE THREAD

**Issue by mark-pitblado** [OpenTermsArchive/contrib-declarations#1235]
The link featured in the repository https://github.com/OpenTermsArchive/contrib-declarations, returns a 404 as of Thursday November 30 2023 (date of this issue)

**Comment by MattiSG** [comment]
Thanks for the heads up @mark-pitblado! The link should be https://docs.opentermsarchive.org/navigate-history/. I've just corrected it 🙂
