### ISSUE TITLE
National Geographic tracks Disney ToS and PPolicy

### ISSUE THREAD

**Issue by Kissaki** [OpenTermsArchive/contrib-declarations#727]
The service is labeled _National Geographic_ but the terms and privacy policy are from _Disney_ (and link to Disney webpages).

Shouldn’t Disney be tracked as Disney, and if National Geographic refers to Disney only, it does not have any ToS and PPolicy?

[declarations/National Geographic.json](https://github.com/OpenTermsArchive/contrib-declarations/blob/main/declarations/National%20Geographic.json)

**Comment by MattiSG** [comment]
Thanks for having taken the time to review this existing declaration! 

If I go on https://www.nationalgeographic.com, I do see the following links in the footer:

- Terms of Use: https://disneytermsofuse.com/
- Privacy Policy: https://privacy.thewaltdisneycompany.com/en/current-privacy-policy/

This declaration thus seems accurate 🙂
